default: &default
   adapter: postgresql
   encoding: unicode
   host: localhost
   port: 5432
   database: invoice
   username: postgres
   password: postgres
  
development:
   <<: *default

test:
   <<: *default
 
production:
   <<: *default